### PR TITLE
Add `cabal new-build` support

### PR DESCRIPTION
**Pull request by hamishmack**
@jaccokrijnen, @JPMoresmau can you please try out the [new-build branch](https://github.com/leksah/leksah/tree/new-build) when you have a chance and let me know if it works for you.  If it seems ok we can merge it into master.

The documentation for `cabal new-build` can be found [here](http://blog.ezyang.com/2016/05/announcing-cabal-new-build-nix-style-local-builds/).  Here is what I had planned for Leksah support:

* Switch from `cabal build`, `cabal repl` ... to `cabal new-build`, `cabal new-repl`... (IN PROGRESS).

* Remove `cabal sandbox` support (DONE).

* Remove `cabal-dev` support (DONE).

* Only use `stack` if a `cabal.project` is not found and a `stack.yaml` is (TODO).

One nice thing about it already (compared to `stack`) is that Leksah triggers builds nicely when changes are made to a package listed in the `cabal.project` file.  This is because `cabal new-build` behaves much more like `cabal build` than `stack build` does (in particular you can run `cabal new-build` in any subdirectory of the one containing the `cabal.package` and it will build that package).  Add `leksah.cabal` and whatever submodule `.cabal` file you are working on to your workspace and changes in those packages should trigger builds.

### CODE REVIEW

**Comment by jaccokrijnen** [comment]
I'll give it a try when I get back home. Nog sure about removing sandbox support, many people might still rely on sandboxes also plus new-build is still in "beta".

**Comment by JPMoresmau** [comment]
I can't even build master :-(

**Comment by jaccokrijnen** [comment]
Me neither:
```
jacco@xw4600:~/projects/leksah/leksah$ cabal new-build lib:leksah
In order, the following will be built (use -v for more details):
gi-cairo-1.0.4
gi-glib-2.0.4
gi-gobject-2.0.4
gi-atk-2.0.4
gi-gio-2.0.4
gi-gdkpixbuf-2.0.4
gi-javascriptcore-3.0.4
gi-pango-1.0.4
gi-gdk-3.0.4
gi-gtk-3.0.4
gi-gtk-hs-0.3.0.0
gi-gtksource-3.0.4
gi-soup-2.4.4
gi-webkit-3.0.4
lens-4.14
jsaddle-0.4.0.1
jsaddle-dom-0.1.0.1
ghcjs-dom-0.3.1.0
ltk-0.16.0.0
leksah-server-0.16.0.0
vcsgui-0.2.0.0
leksah-0.16.0.0
unrecognized 'configure' option `--profiling-detail=default'

unrecognized 'configure' option `--library-profiling-detail=default'

unrecognized 'configure' option `--ipid=gi-cairo-1.0.4-inplace'

```

I'm guessing there's something wrong with my cabal? I can't find any if these config options in cabal's files.

```
jacco@xw4600:~/projects/leksah/leksah$ cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 

```

**Comment by jaccokrijnen** [comment]
Maybe it's because I only recently upgraded to cabal 1.24. I've removed ~/.cabal/bin and ./dist-newstyle and trying a fresh build right now.

**Comment by hamishmack** [comment]
@jaccokrijnen check if you have a `cabal.project.local` file.

**Comment by hamishmack** [comment]
@jaccokrijnen I added a step to the Readme

    cabal install ./vendor/haskell-gi ./vendor/haskell-gi-base

That I think might also be a good idea.  I am not 100% sure `cabal new-build` picks up haskell-gi from the right place (if it gets it wrong it might still take a long time to build because it will include all the overloading code).

**Comment by jaccokrijnen** [comment]
A clean build made no difference. I did get a `cabal.project.local` file when doing `cabal new-configure` but it's empty. Still getting the unrecognized configure options somehow. I suppose you meant `cabal new-build ...` for those deps? `install` uses the sandbox which is ignored by `new-build`, right?

**Comment by hamishmack** [comment]
Might be related to this https://github.com/haskell/cabal/issues/3433.

I think you might need to have the latest Cabal, gtk2hs-buildtools and haskell-gi in the `ghc-pkg list`.

**Comment by hamishmack** [comment]
> I'll give it a try when I get back home. Not sure about removing sandbox support, many people might still rely on sandboxes plus new-build is still in "beta".

True.

I think we should make a clean break with sandboxes though (I am not too fussed when it happens).   The interface will get really messy if we keep the sandbox support as it is and add `cabal new-build`.  Updating sandbox support to work more like how we can do things with `cabal new-build` will create a lot of work.

Perhaps we should release Leksah 0.16 without `cabal new-build` and then put out a Leksah 0.17 with it merged in.  People who need sandbox support can stick with 0.16.

**Comment by hvr** [comment]
@hamishmack if you're interested, I recently switched hackage-server's Travis job to use new-build (the script diverges a bit from what the v2-travis-script generator currently does, but I'll merge this back into the script generator soon): https://github.com/haskell/hackage-server/blob/master/.travis.yml

Build-times are now down to ~5-6 minutes (previously ~15-20 minutes)

**Comment by dcoutts** [comment]
@hamishmack @JPMoresmau could you make sure there's a ticket for the `unrecognized 'configure' option ...` issue, and if at all possible make sure there's details for a reproducible case. It's undoubtedly a problem with talking to a Setup.hs built with an older version of the Cabal lib, but this is something that we want to work.

**Comment by hamishmack** [comment]
@hvr that is awesome.

**Comment by hamishmack** [comment]
@dcoutts I've not had it myself.  @JPMoresmau did your build fail with the same error as @jaccokrijnen ?

**Comment by hamishmack** [comment]
@jaccokrijnen try `cabal new-build --constraint='Cabal>=1.24'`

**Comment by jaccokrijnen** [comment]
It builds! I don't quite understand why `haskell-gi` has to be in ghc-pkg list (as far as I understand, `new-build` only searches at `~/.cabal/store` and `./dist-newstyle/`, while ghc-pkg/cabal install use the old library locations)

Still a problem left with `cabal new-repl`:

```
jacco@xw4600:~/projects/leksah/leksah$ cabal new-repl
In order, the following will be built (use -v for more details):
leksah-0.16.0.0
Preprocessing library leksah-0.16.0.0...
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
<command line>: can't load .so/.DLL for: /home/jacco/projects/leksah/leksah/dist-newstyle/build/gi-webkit-3.0.4/build/libHSgi-webkit-3.0.4-inplace-ghc7.10.3.so (/home/jacco/projects/leksah/leksah/dist-newstyle/build/gi-webkit-3.0.4/build/libHSgi-webkit-3.0.4-inplace-ghc7.10.3.so: undefined symbol: webkit_check_version)
```

**Comment by hvr** [comment]
@jaccokrijnen strictly speaking,  `new-build` does  look in `ghc-pkg list --global` out of necessity, otherwise `ghc-prim`/`integer-gmp` etc wouldn't be available

**Comment by jaccokrijnen** [comment]
@hvr Ok, but it doesn't use the user database, right?

**Comment by jaccokrijnen** [comment]
@hamishmack I found that (on my machine) it also compiles without having `haskell-gi` and `haskell-gi-base` and `Cabal-1.24.x` installed seperately. I do get the occasional

```
Warning: Exception was: user error (The package 'gi-javascriptcore' requires
Cabal library version >=1.18.0 && >=1.24 but no suitable version is
installed.)
```
but it doesn't seem to hinder the actual building.

**Comment by hamishmack** [comment]
> Still a problem left with `cabal new-repl`

There is a [fix for this in github](https://github.com/haskell-gi/haskell-gi/blob/master/bindings/WebKit/WebKit.overrides#L8), but it is not in Hackage yet.

To build and use the `gi-*.cabal` files locally run:

```
cabal install aeson aeson-pretty
cabal install vendor/haskell-gi vendor/haskell-gi-base
cd vendor/haskell-gi/bindings
for a in `./PKGS.sh`; do ./genBuildInfo.hs $a; done
cd ../../..
cp cabal.project.gi-bindings cabal.project
cabal new-build
```

I think this might also be necessary to build Leksah with older versions of Gtk+ (we have added a bunch of overrides to flag parameters and return values as nullable).

@garetxe could you please release x.x.5 versions of the `gi-*.cabal` packages to Hackage?

**Comment by garetxe** [comment]
Sure, done!

**Comment by hamishmack** [comment]
If you are building this branch please note that I have updated the Readme.md instructions.   It will get simpler again once the changes to haskell-gi (new flags that disable overloading) are in hackage.

**Comment by hamishmack** [comment]
I have merged the non `new-build` related changes into `master` and rebased this `new-build` branch.

**Comment by hamishmack** [comment]
I have sorted out most of the issues with the `cabal new-build` branch.  In particular running tests now work and @hvr helped with code to parse the `plan.json` file (replacing the need for packages to be in `ghc-pkg list`).  I don't think we need to support `cabal build` any more so I have merged the `new-build` branch into `master`.

One thing that it would be nice to fix is that system metadata is not updated properly with `Tools -> Update System Data` menu item (and `Tools -> Rebuild System Data` takes ages to run since it starts from scratch).  Instead the best way right now to update the system metadata is to build a package (so that the `plan.json` file will have something in it) then restart Leksah (at startup the system metadata is updated).

**Comment by jaccokrijnen** [comment]
Where can I find more info about the `plan.json` file? What does it contain and why is that better than `ghc-pkg list --package-db=path-to-db`?

**Comment by hamishmack** [comment]
It includes all the packages used by `cabal new-build` for the the given `cabal.project` file (or just the `.cabal` file if there is no `cabal.project`).

Compared to `ghc-pkg list --package-db ~/.cabal/store/ghc-8.0.1/package.db` it:

* Will include packages that are specified by source location in `cabal.project`. Since these are not put in the store.

* Will not include packages not used in the plan.

I was worried that the there would be lots of different versions of the same package in the store (which was not typically the case with the old package databases).  I guess that is not really a big deal since we have the included dependencies checkbox.  Also there will probably be a garbage collector for the store at some point (for now its not a big deal to blow away your store since the rebuild is much more deterministic than the old cabal).

As for the packages listed in the `cabal.project` that will not show up in `ghc-pkg list` file perhaps we are better off just looking in that file and then indexing them as "workspace" packages (since `cabal unpack` may not work and might get the wrong source code anyway).

I'll try `ghc-pkg list --package-db` and parsing `cabal.project`.

**Pull request merged**
