### PR TITLE
Improved errors pane

### PR DESCRIPTION
**Pull request by jaccokrijnen**
I've modified the errors pane in some ways to make it more convenient. Since this changes quite a bit, I made it a PR for a second review.

The most important changes are:

* Buttons for showing/hiding errors/warnings/suggestions
* Added Right Click -> Copy message to clipboard
* Every message takes only one line (long messages used to take up a lot of space)
* Have errors listed per File
* Created some new icons (also added to editor gutter)
* Removed unused Int in ErrorAdded event

errors_pane

### CODE REVIEW

**Comment by jaccokrijnen** [comment]
I accidentally reverted a #200 during rebasing, fixed that again.

**Comment by hamishmack** [comment]
Nice, but the old Errors pane tried to always show the most important message first and you could read the whole message (even if it was long).  Now if I HLint one package then add a compiler error to another the error is not at the top and only the first part of the message may fit on the screen.

Instead of combining the lines of the message, could we make the first line of the message a parent node and put all the other lines in a child node?  Then the user could easily collapse long messages.

Can we keep the order used in the old pane (even if that means having multiple parent items for the same source file)?

I'm also not keen on the filter buttons.  They take up space valuable space and are just one more thing I have to deal with as a user.  If the order of the old pane is used the errors and test failures should show up at the top anyway.

**Comment by jaccokrijnen** [comment]
> Instead of combining the lines of the message, could we make the first line of the message a parent node and put all the other lines in a child node? Then the user could easily collapse long messages.

Sounds like a good idea :) I do like the fact that the lines are combined, so I can see as much of the message without having to expand it.

> Can we keep the order used in the old pane (even if that means having multiple parent items for the same source file)?

I think that would be a bit confusing. Perhaps it would be better then to have no parent file-nodes at all, and save more vertical space (and add a column for file name)?

> I'm also not keen on the filter buttons. They take up space valuable space and are just one more thing I have to deal with as a user. If the order of the old pane is used the errors and test failures should show up at the top anyway.

I really like having the possibility to hide suggestions and warnings, perhaps we could add something like a small cog button that displays a context menu with checked menu items for this? (I would also like to add a setting for filtering only messages of the active project)

**Comment by jaccokrijnen** [comment]
I've changed the order back to what you suggested, messages are expanded by default and you can collapse them (single line messages don't get a child node):

errors

I haven't removed the buttons yet, maybe we could discuss them a bit more. I think they are quite useful, and I don't really see how they would burden the user. The space that they take is quite minimal too (maybe one line of error message output). Maybe we can have a preference to hide this part of the errors pane?

**Comment by hamishmack** [comment]
Looks nice, but can we please put `addErrorToList` back in?  I think it important that adding just one error to the list does not cause it to redraw the whole list.

If the new item does not match the filter settings we can just ignore it.

We should be able to calculate the correct index to use in the filtered list by counting the number of items before the raw index that match the current filter settings.

**Comment by jaccokrijnen** [comment]
> Looks nice, but can we please put addErrorToList back in? I think it important that adding just one error to the list does not cause it to redraw the whole list.

Wouldn't it be better to have only one way of settings errors, by updating the ide state? I can try avoid unnecessary redraws in `fillErrorsPane` (I'll rename to `refreshErrorsPane`).

**Comment by hamishmack** [comment]
IIRC I did try something like that, but it involved comparing lots of LogRefs and and they contain large text fields it all starts to add up.  LogRefs are added one at a time and if you diff the the whole set to find the ones that were added it winds up slow.  I was doing an O(N) search for diffs (so over all it was O(N^2) for to add N messages) and perhaps we could do better (we could hash the large fields in LogRef).

I think it is simpler though to include `addErrorToList` though since we know in the code that adds the LogRef which one is being added (and where) and we don't need to compare any of the message text fields.

**Comment by hamishmack** [comment]
As test for the performance issues I tried this:

    module Main (main) where

    main = putStrLn "Hello, World!"

    a = x
    a = x
    ...

With about 2000 `a = x` lines the current master branch (on my OS X build) freezes for a few seconds when builds happen, but this new branch locks up the UI for minutes.

Also when moving the cursor around the code (when there are 2000 errors) the UI locks up (I presume in the code selecting the current error in the pane).  This does not happen at all in the current master branch.

**Comment by jaccokrijnen** [comment]
I've added `addErrorToList` back in. It seems to fix the extreme UI lockups for me (Ubuntu) that happened in your test with 2000 errors. Does it also work for you on OSX?

**Comment by hamishmack** [comment]
Sorry last few weekends I have been busy trying to sort out jsaddle and jsaddle-dom out.  This does indeed fix it.

**Pull request merged**
