### PR TITLE
Fix brackets in PATH oneliner

### PR DESCRIPTION
**Pull request by Anton-Latukha**
* _Fix brackets in PATH oneliner_
I made an error, noticed it, fixed it.
"$SHELL"' -c '"echo $PATH" was returning '/bin/bash -c echo _PATH_' instead of value.

* _changing PATH oneliner to little script_
This is additional expansion. It  has more clear algorithm and more clear for understanding, it finds and changes value directly.
`^PATH=*` not matching line if it is `export PATH=` or what if it is `PATH="`.

Accepting or not last commit, I already spent time, so going to save this and expand, and commit to Stack auto-install, if I already spent time and started.

Thank you.
Shell scripts are being shell scripts.

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
Please  merge at least 'Fix brackets in PATH oneliner'.

I've done nasty error in previous pull.

I need create to myself good shell debuging workflow.

**Comment by hamishmack** [comment]
Sorry I only just had time to look at this.  I don't think adding to PATH like that will work for a lot of people.  For instance I have set up my `PATH` in `~/.profile` (so it will fail to find it in `.bashrc`).  When I do add things to the `PATH` it is always like this

    export PATH=/usr/local/bin:$PATH
    export PATH=$HOME/.cabal/bin:$PATH

Searching for the entire old $PATH will not work.

If anything I think we should just append to the rc file.

    export PATH=$HOME/.cabal/bin:$PATH

Adding things to ones PATH is a basic skill that might be better explained elsewhere.  Is there a good tutorial online we could link to?  If not I think we should split it out into a separate `HowToSetupPATH.md` file.

**Comment by hamishmack** [comment]
I have removed the stuff about setting PATH from the main readme for now.  Please feel free to add a link to separate `.md` file or some other tutorial(s) on configuration of PATH.

**Comment by Anton-Latukha** [comment]
Yes.
You are right.

~/.profile and everything.

I also think reverting it is probably true. Situation is too spread.

**Pull request merged**
