### PR TITLE
Fixed issue that prevented leksah from building

### PR DESCRIPTION
**Pull request by edouardpoitras**
Signed-off-by: Edouard Poitras <edouardpoitras@gmail.com>

### CODE REVIEW

**Comment by edouardpoitras** [comment]
I was getting the following errors when following the stack build steps and running `stack install`:
```
/home/eddie/Projects/leksah/src/IDE/Statusbar.hs:85:34-81: error:
        • Couldn't match expected type ‘Text’
                      with actual type ‘Maybe [Char]’
        • In the second argument of ‘imageSetFromIconName’, namely
            ‘(Just $ if bool then "ide_build" else "ide_empty")’
          In a stmt of a 'do' block:
            imageSetFromIconName
              im
              (Just $ if bool then "ide_build" else "ide_empty")
              (fromIntegral . fromEnum $ IconSizeMenu)
          In the expression:
            do { im <- getImBuild;
                 imageSetFromIconName
                   im
                   (Just $ if bool then "ide_build" else "ide_empty")
                   (fromIntegral . fromEnum $ IconSizeMenu);
                 return () }
    
    /home/eddie/Projects/leksah/src/IDE/Statusbar.hs:89:34-88: error:
        • Couldn't match expected type ‘Text’
                      with actual type ‘Maybe [Char]’
        • In the second argument of ‘imageSetFromIconName’, namely
            ‘(Just $ if bool then "ide_rebuild_meta" else "ide_empty")’
          In a stmt of a 'do' block:
            imageSetFromIconName
              im
              (Just $ if bool then "ide_rebuild_meta" else "ide_empty")
              (fromIntegral . fromEnum $ IconSizeMenu)
          In the expression:
            do { im <- getImCollect;
                 imageSetFromIconName
                   im
                   (Just $ if bool then "ide_rebuild_meta" else "ide_empty")
                   (fromIntegral . fromEnum $ IconSizeMenu);
                 return () }
    
    /home/eddie/Projects/leksah/src/IDE/Statusbar.hs:119:41-56: error:
        • Couldn't match expected type ‘Text’
                      with actual type ‘Maybe [Char]’
        • In the first argument of ‘imageNewFromIconName’, namely
            ‘(Just "ide_empty")’
          In a stmt of a 'do' block:
            buildImage <- imageNewFromIconName
                            (Just "ide_empty") (fromIntegral $ fromEnum IconSizeMenu)
          In the expression:
            do { sblk <- statusbarNew;
                 widgetSetName sblk "statusBarSpecialKeys";
                 widgetSetSizeRequest sblk 150 (- 1);
                 sbap <- statusbarNew;
                 .... }
    
    /home/eddie/Projects/leksah/src/IDE/Statusbar.hs:123:43-58: error:
        • Couldn't match expected type ‘Text’
                      with actual type ‘Maybe [Char]’
        • In the first argument of ‘imageNewFromIconName’, namely
            ‘(Just "ide_empty")’
          In a stmt of a 'do' block:
            collectImage <- imageNewFromIconName
                              (Just "ide_empty") (fromIntegral $ fromEnum IconSizeMenu)
          In the expression:
            do { sblk <- statusbarNew;
                 widgetSetName sblk "statusBarSpecialKeys";
                 widgetSetSizeRequest sblk 150 (- 1);
                 sbap <- statusbarNew;
                 .... }
```

**Comment by hamishmack** [comment]
It looks like the latest gi-gtk overrides are not working for some reason.  Can you check what version of gi-gtk is being used?  It should be 3.0.13.

**Comment by hamishmack** [comment]
Oh the leksah stack.yaml file needs updating.

**Comment by hamishmack** [comment]
This should be resolved by https://github.com/leksah/leksah/commit/90041502b3ae0ceb6f8828342ce96fefbd39b970.

**Comment by edouardpoitras** [comment]
Thanks!

**Pull request closed without merging**
