### PR TITLE
Readme.md: update to Fedora 23 docker image

### PR DESCRIPTION
**Pull request by juhp**
Untested but I think this should work.

### CODE REVIEW

**Comment by hamishmack** [comment]
I think I tested that a while back and there were some mingw gtk or webkitgtk issues.  It was a long time ago though and the packages have probably been updated.  I'll try it out tomorrow.

**Comment by juhp** [comment]
Sure, just a suggestion. F22 is still a current release for some more
months.

**Comment by hamishmack** [comment]
This is blocked by ["JavaScriptCore LLInt fails to build for 64 bit; disable it for now."](http://pkgs.fedoraproject.org/cgit/rpms/mingw-webkitgtk.git/commit/mingw-webkitgtk.spec?h=f22&id=25ed39873b1aa54305eb5d4b072701caf264890f).

Hi @kalev do you know if this issue has been fixed yet?

**Comment by hamishmack** [comment]
This has been updated now.  It uses a patch to build the missing webkitgtk.  Image is still broken, but only because we need to find a way to `#ifdef` out some haskell-gi on Windows.

**Pull request closed without merging**
