### PR TITLE
Easy peasy message dialogs

### PR DESCRIPTION
**Pull request by jpaugh**
Refactor most uses of MessageDialog so that they share common code. Not only does this get rid of a couple of memory leaks, it also ensures consistency between most dialogs in the app, and makes the source code much easier to read

### CODE REVIEW

**Comment by jpaugh** [comment]
This is a pretty substantial change, so I ordered the commits from least substantial to most substantial. I also took care to separate my changes into logical progressions, so that I was not changing too much at once and the individual commit diffs remain readable and (hopefully) easily verifiable.

Each commit compiles, so if you want to skip some of the later commits, you can. In particular, the last commit is one of my favorites, which is a good sign that it goes too far ;-)

**Comment by jpaugh** [comment]
This ran for 50mins before being terminated by Travis

> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by jpaugh** [comment]
I accidentally closed the wrong PR. Whoops!

**Comment by hamishmack** [comment]
Awesome! The the amount of duplicated mess around showing dialogs has always bugged me.

**Comment by jpaugh** [comment]
Sweet! Thanks! I was a bit worried this commit might get plagued by merge conflicts.

**Pull request merged**
